services:
  user-data-generator:
    image: ghcr.io/kukv/kamidata-cli:latest
    volumes:
      - ${PWD}/generated:/generated
      - ${PWD}/templates:/templates
      - ${PWD}/values:/values
      - ${PWD}/values-secret:/values-secret
    command: >
      /templates/user-data.j2
      --data /values/${MACHINE_NAME}.json
      --data /values-secret/${MACHINE_NAME}.json
      --dst /generated/${MACHINE_NAME}/user-data
